### PR TITLE
fix/DS-248-secondary-lists updated list types

### PR DESCRIPTION
**Pull request by Juliet-Brown**
- Updated list types` ul `should be circle and  `ol`should be lower alpha [DS-248](https://govtnz.atlassian.net/browse/DS-248) .

### CODE REVIEW

**Comment by holloway** [comment]
Hey @Juliet-Brown this one will also need updating in the `template-sources` directory and then re-run `yarn build` to generate the scss/css

**Comment by holloway** [comment]
Also, should the fix use a nested selector ie `.g-ol { default styling}  .g-ol .g-ol { secondary list styling } `

**Comment by Juliet-Brown** [comment]
Updated to templates @holloway . Do you mean it should be also applied to` .g-ol .g-ol { secondary list styling } ` ?

**Comment by holloway** [comment]
@Juliet-Brown Sort of, I mean that my reading of this task is that we want different styling for 1st level vs 2nd level lists.

So the g-ol styling should remain as-is. The nested g-ol styling for 2nd level should be different.

**Comment by Juliet-Brown** [comment]
Pushed up updates @holloway .

**Pull request merged**
